apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-pv-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-pv-volume
  namespace: kube-system
spec:
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      volumes:
        - name: elasticsearch-cfg
          configMap:
            name: elasticsearch-config
        - name: pv-storage
          persistentVolumeClaim:
              claimName: elastic-pv-volume
      containers:
      - name: elasticsearch
        image: elasticsearch:8.1.3
        env:
        - name: discovery.type
          value: single-node
        volumeMounts: 
          -  mountPath: "/usr/share/elasticsearch/config"
             name: elasticsearch-cfg
             subPath: "elasticsearch.yml"  
          -  mountPath: "/usr/share/elasticsearch/config"
             name: elasticsearch-cfg
             subPath: "jvm.options"    
          -  mountPath: "/var/lib/elasticsearch"
             name: pv-storage
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 2Gi

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: kube-system
  labels:
   service: elasticsearch-logging
spec:
  type: NodePort
  selector:
    component: elasticsearch
  ports:
  - port: 9200
    targetPort: 9200