kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-config
  namespace: kube-logging
data:
  fluent.conf: |-
       @include pods-kind-fluent.conf
       @include pods-fluent.conf
       @include file-fluent.conf
       @include mongo-fluent.conf
  pods-kind-fluent.conf: |-
    <source>
      @type tail
      read_from_head true
      tag mongo.application
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      exclude_path ["/var/log/containers/fluent*"]
      <parse>
         @type regexp
         expression /^\[(?<logtime>[^\]]*)\] (?<Entering>[^ ]*) (?<PARAMS>[^ ]*)/ig
         expression /^\[(?<logtime>[^\]]*)\] (?m)^.*?Exception.*(?:\R+^\s*at .*)+/ig
         time_key logtime
         time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>
     <filter mongo.**>
        @type kubernetes_metadata
        @id filter_kube_metadata
        kubernetes_url "#{ENV['FLUENT_FILTER_KUBERNETES_URL'] || 'https://' + ENV.fetch('KUBERNETES_SERVICE_HOST') + ':' + ENV.fetch('KUBERNETES_SERVICE_PORT') + '/api'}"
        verify_ssl "#{ENV['KUBERNETES_VERIFY_SSL'] || false}"
        ca_file "#{ENV['KUBERNETES_CA_FILE']}"
        skip_labels "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_LABELS'] || 'false'}"
        skip_container_metadata "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_CONTAINER_METADATA'] || 'false'}"
        skip_master_url "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_MASTER_URL'] || 'false'}"
        skip_namespace_metadata "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_NAMESPACE_METADATA'] || 'false'}"
        watch "#{ENV['FLUENT_KUBERNETES_WATCH'] || 'true'}"
    </filter>
  pods-fluent.conf: |-
    <source>
      @type tail
      read_from_head true
      tag file.application
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers-pods.log.pos
      exclude_path ["/var/log/containers/fluent*"]
      <parse>
         @type kubernetes
         @type "#{ENV['FLUENT_CONTAINER_TAIL_PARSER_TYPE'] || 'json'}"
         time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>
  file-fluent.conf: |-
   <match file.**>
      @type file
      path /var/log/fluent/archived
      compress gzip
      <buffer>
        timekey 1d
        timekey_use_utc true
        timekey_wait 10m
      </buffer>
    </match>
  mongo-fluent.conf: |-
      <match mongo.**>
        @type mongo
        host mongo.kube-logging.svc.cluster.local
        port 27017
        database fluentld
        collection kubelog
        capped
        capped_size 1024m
        user mongoadmin
        password secret123
        time_key time
        flush_interval 10s
      </match>