apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/ssl/kube-ca.pem
"authorization": {
    "mode": "Webhook",
    "webhook": {
      "cacheAuthorizedTTL": 20s,
      "cacheUnauthorizedTTL": 20s
    }
  }
clusterDNS:
- 10.43.0.10
clusterDomain: cluster.local
cpuManagerReconcilePeriod: 0s
evictionPressureTransitionPeriod: 0s
fileCheckFrequency: 0s
healthzBindAddress: 127.0.0.1
healthzPort: 10248
httpCheckFrequency: 0s
imageMinimumGCAge: 0s
kind: KubeletConfiguration
nodeStatusReportFrequency: 0s
nodeStatusUpdateFrequency: 0s
rotateCertificates: true
runtimeRequestTimeout: 0s
staticPodPath: /etc/kubernetes/manifests
streamingConnectionIdleTimeout: 0s
volumeStatsAggPeriod: 0s
syncFrequency: 20s
fileCheckFrequency : 20s
httpCheckFrequency : 20s
address : 0.0.0.0
port : 10250
tlsCertFile : "/var/lib/kubelet/pki/kubelet.crt"
tlsPrivateKeyFile : "/var/lib/kubelet/pki/kubelet.key"
