apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: java-demo-ns
spec:
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: java-demo-ns
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: mysql-pv-claim
  containers:
     - name: mysql-server
       image: mysql:latest
       ports:
         - containerPort: 3306
           protocol: TCP
       env:
          - name: MYSQL_ROOT_PASSWORD
            value: Swam2@mysql
       volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: pv-storage
          
          