apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: java-demo-ns
spec:
  selector:
    matchLabels:
      run: nfs-server
  replicas: 1
  template:
    metadata:
      labels:
        run: nfs-server
    spec:
      nodeSelector:     
        kubernetes.io/hostname: k8s-playground-worker
      containers:
        - name: nfs-server
          image: itsthenetwork/nfs-server-alpine:latest
          securityContext:
            capabilities:
                add: ["SYS_ADMIN", "SETPCAP"]
          ports:
          - name: nfs  
            containerPort: 2049
          env:
          - name: SHARED_DIRECTORY
            value: "/nfsshare"
          volumeMounts:
          - name: nfs-storage
            mountPath: /nfsshare
      volumes:
         - name: nfs-storage  
           hostPath: 
            path:  "/var/data"