nodes:
    - address: 10.1.50.38
      user: root
      role:
        - controlplane
        - etcd
      hostname_override: masternode
      port: 22
    - address: 10.1.50.252
      user: root
      role:
        - worker
      hostname_override: kubeWorker
      port: 22


ignore_docker_version: false
ssh_key_path: /home/admin/.ssh/id_rsa

private_registries:
    - url: docker.io
      user: avijit1979
      password: Lotus2ibm
cluster_name: k8s-playground
kubernetes_version: v1.22.6-rancher1-1
services:
    etcd:
    kube-api:
      service_cluster_ip_range: 10.43.0.0/16
      service_node_port_range: 30000-32767    
      pod_security_policy: false
      extra_args:
        audit-log-path: "/var/log/kube-access.log"
        delete-collection-workers: 3
        v: 4
    kube-controller:
      cluster_cidr: 10.42.0.0/16
      service_cluster_ip_range: 10.43.0.0/16
      extra_args:
        v: 4
        feature-gates: RotateKubeletServerCertificate=true
        cluster-signing-cert-file: "/etc/kubernetes/ssl/kube-ca.pem"
        cluster-signing-key-file: "/etc/kubernetes/ssl/kube-ca-key.pem"
    kubelet:
      cluster_domain: cluster.local
      cluster_dns_server: 10.43.0.10
      fail_swap_on: false
      pod-infra-container-image: "k8s.gcr.io/pause:3.2"
      generate_serving_certificate: true
      extra_args:
          v: 4
          max-pods: 250
          feature-gates: RotateKubeletServerCertificate=true
      extra_binds:
        - "/dev/kmsg:/dev/kmsg:z"
        - "/usr/libexec/kubernetes/kubelet-plugins:/usr/libexec/kubernetes/kubelet-plugins:z"
        - "/var/lib/kubelet:/var/lib/kubelet:z"
    scheduler:
      extra_args:
        v: 4
    kubeproxy:
       extra_args:
         v: 4
network:
    plugin: canal
    options: {}
authentication:
      strategy: x509
      options: {}
      sans:
        - "masternode.cluster.local"
        - "kubeWorker.cluster.local"
dns:
    provider: coredns
ingress:
    provider: nginx
    node_selector:
      app: ingress
      
addons: |-
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: nginx-proxy
      namespace: default
    spec:
      containers:
      - name: nginx-proxy
        image: nginx
        ports:
        - containerPort: 80
