nodes:
    - address: 10.1.50.38
      user: root
      role:
        - controlplane
        - etcd
      hostname_override: masternode
      port: 22
    - address: 10.1.50.252
      user: root
      role:
        - worker
      hostname_override: kubeWorker
      port: 22


ignore_docker_version: false
ssh_key_path: /home/admin/.ssh/id_rsa

private_registries:
    - url: docker.io
      user: avijit1979
      password: Lotus2ibm
cluster_name: k8s-plyground
services:
    etcd:
      image: rancher/coreos-etcd:v3.4.16-rancher1
      extra_args: {}
      extra_binds: []
      external_urls: []
      ca_cert: ""
      cert: ""
      key: ""
      path: ""
      snapshot: false
      retention: ""
      creation: ""
    kube-api:
      image: rancher/hyperkube:v1.23.5-rancher1
      service_cluster_ip_range: 10.43.0.0/16
      service_node_port_range: 30000-32767    
      pod_security_policy: false
      extra_args:
        audit-log-path: "-"
        delete-collection-workers: 3
        v: 4
    kube-controller:
      image: rancher/hyperkube:v1.23.5-rancher1
      cluster_cidr: 10.42.0.0/16
      service_cluster_ip_range: 10.43.0.0/16
    kubelet:
      image: rancher/hyperkube:v1.23.5-rancher1
      cluster_domain: cluster.local
      cluster_dns_server: 10.43.0.10
      fail_swap_on: false
      extra_args:
          max-pods: 250
          feature-gates : "RotateKubeletClientCertificate=true,RotateKubeletServerCertificate=true"
      extra_binds:
        - "/dev/kmsg:/dev/kmsg"
        - "/var/lib/rancher:/var/lib/rancher"
        - "/var/lib/kubelet:/var/lib/kubelet"
        - "/usr/libexec/kubernetes/kubelet-plugins:/usr/libexec/kubernetes/kubelet-plugins"
    kubeproxy:
      image: rancher/hyperkube:v1.23.5-rancher1
      extra_args: {}
      extra_binds: []
network:
    plugin: canal
    options: {}
authentication:
      strategy: x509
      options: {}
      sans:
        - "masternode.cluster.local"
        - "kubeWorker.cluster.local"
dns:
    provider: coredns
ingress:
    provider: nginx
    node_selector:
      app: ingress
      
addons: |-
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: nginx-proxy
      namespace: default
    spec:
      containers:
      - name: nginx-proxy
        image: nginx
        ports:
        - containerPort: 80
