nodes:
    - address: 10.1.50.38
      user: root
      role:
        - controlplane
        - etcd
      hostname_override: masternode.cluster.local
      port: 22
    - address: 10.1.50.252
      user: root
      role:
        - worker
      hostname_override: kubeWorker.cluster.local
      port: 22


ignore_docker_version: false
ssh_key_path: /home/admin/.ssh/id_rsa

private_registries:
    - url: docker.io
      user: avijit1979
      password: Lotus2ibm
cluster_name: k8s-plyground

kubernetes_version: v1.22.6-rancher1-1

services:
    etcd:
    kube-api:
      service_cluster_ip_range: 10.43.0.0/16
      service_node_port_range: 30000-32767    
      pod_security_policy: false
      extra_args:
        audit-log-path: "-"
        delete-collection-workers: 3
        v: 4
    kube-controller:
      cluster_cidr: 10.42.0.0/16
      service_cluster_ip_range: 10.43.0.0/16
    kubelet:
      cluster_domain: cluster.local
      cluster_dns_server: 10.43.0.10
      fail_swap_on: false
      extra_args:
        max-pods: 250
      extra_binds:
        - "/usr/libexec/kubernetes/kubelet-plugins:/usr/libexec/kubernetes/kubelet-plugins"
    kubeproxy:
      extra_args: {}
      extra_binds: []
network:
    plugin: canal
    options: {}
    authentication:
      strategy: x509
      options: {}
      sans:
        - "masternode.cluster.local"
        - "kubeWorker.cluster.local"
dns:
    provider: coredns
ingress:
    provider: nginx
    node_selector:
      app: ingress
      
addons: |-
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: nginx-proxy
      namespace: default
    spec:
      containers:
      - name: nginx-proxy
        image: nginx
        ports:
        - containerPort: 80
